CREATE TABLE orders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_type TEXT NOT NULL,
    address TEXT,
    mobile_number TEXT,
    order_complete BOOLEAN DEFAULT FALSE NOT NULL,
    time_ready TIMESTAMP,
    time_placed TIMESTAMP,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL
);