CREATE TABLE order_item (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    size_large BOOLEAN NOT NULL,
    size_medium BOOLEAN NOT NULL,
    size_small BOOLEAN NOT NULL,
    price_large DECIMAL DEFAULT 0.00 NOT NULL,
    price_medium DECIMAL DEFAULT 0.00 NOT NULL,
    price_small DECIMAL DEFAULT 0.00 NOT NULL,
    ingredients TEXT [] DEFAULT '{}' NOT NULL,
    price DECIMAL DEFAULT 0.00 NOT NULL,
    order_id INTEGER NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL
);