CREATE TABLE item_ingredients (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category TEXT NOT NULL,
    type TEXT,
    name TEXT NOT NULL,
    price_none DECIMAL DEFAULT 0.00,
    price_add DECIMAL,
    price_half DECIMAL,
    price_double DECIMAL,
    price_extra DECIMAL
);

INSERT INTO item_ingredients
(category, type, name, price_add, price_half, price_double, price_extra)
VALUES
(
    'Pizza',
    'Sauce',
    'Tomato sauce',
    1,
    .50,
    2.00,
    1.50
),
(
    'Pizza',
    'Cheese',
    'No Mozzarela cheese',
    4.00,
    2.00,
    6.00,
    5.00
),
(
    'Pizza',
    'Cheese',
    'Mozzarela cheese',
    4.00,
    2.00,
    6.00,
    5.00
),
(
    'Hero',
    'Cheese',
    'Mozzarella cheese',
    1.00,
    .50,
    3.00,
    2.00
),
(
    'Hero',
    'Sauce',
    'Tomato sauce',
    1.00,
    .50,
    3.00,
    2.00
);