CREATE TABLE menu_items (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    size_large TEXT,
    size_medium TEXT,
    size_small TEXT,
    price_large DECIMAL,
    price_medium DECIMAL,
    price_small DECIMAL,
    ingredients TEXT [] DEFAULT '{}' NOT NULL
);

INSERT INTO menu_items
(category, name, description, ingredients, size_small, size_medium, size_large, price_small, price_medium, price_large)
VALUES
(
    'Pizza',
    'Neopolitan pizza',
    'Regular round pizza with tomato sauce, mozzarella cheese, grated cheese, and oregano',
    '{Tomato sauce, Mozzarela cheese, Grated cheese, Oregano}',
    '10 inch',
    '14 inch',
    '18 inch',
    10.95,
    12.95,
    14.95
),
(
    'Pizza',
    'Margherita pizza',
    'Fresh mozzarella cheese, fresh marinara sauce, basil, oregano, extra virgin oil',
    '{Fresh mozzarella cheese, Fresh marinara sauce, Basil, Oregano, Virgin oil}',
    '10 inch',
    '14 inch',
    '18 inch',
    12.95,
    16.95,
    18.95
),
(
    'Pizza',
    'Sicilian pizza',
    'Thick and light square pizza with our special sauce and melted mozzarela with grated cheese and oregano',
    '{Special sauce, Mozzarella cheese, Grated cheese, Oregano}',
    '10 inch',
    '14 inch',
    '18 inch',
    10.95,
    12.95,
    14.95
),
(
    'Pasta',
    'Alfredo pasta',
    'Creamy alfredo sauce with grated parmigiano cheese',
    '{Alfredo sauce, Grated cheese}',
    '7 oz',
    '11 oz',
    '15 oz',
    6.95,
    8.95,
    10.95
),
(
    'Pasta',
    'Baked ziti',
    'Penne mixed with tomato sauce, ricotta, and topped with mozzarella cheese',
    '{Tomato sauce, Ricotta, Mozzarella cheese}',
    '7 oz',
    '11 oz',
    '15 oz',
    6.95,
    8.95,
    10.95
),
(
    'Pasta',
    'Penne al vodka',
    'Creamy pink vodka with diced imported proscuitto and onion',
    '{Vodka sauce, Diced prosciutto, Onion}',
    '7 oz',
    '11 oz',
    '15 oz',
    6.95,
    8.95,
    10.95
),
(
    'Hero',
    'Chicken parmagiana hero',
    'Fried breaded chicken cutlet topped with tomato sauce, and melted mozzarella cheese',
    '{Fried chicken cutlet, Tomato sauce, Mozzarella cheese}',
    '6 inches',
    null,
    '12 inches',
    5.99,
    0.00,
    8.99
),
(
    'Hero',
    'Meatball parmagiana hero',
    'Meatballs topped with tomato sauce, and melted mozzarella cheese',
    '{Meatballs, Tomato sauce, Mozzarella cheese}',
    '6 inches',
    null,
    '12 inches',
    5.99,
    0.00,
    8.99
),
(
    'Hero',
    'Veal parmagiana hero',
    'Fried breaded veal topped with tomato sauce, and melted mozzarella cheese',
    '{Veal, Tomato sauce, Mozzarella cheese}',
    '6 inches',
    null,
    '12 inches',
    5.99,
    0.00,
    8.99
);
